# Generated by Django 2.2.17 on 2021-02-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=18598070915, max_length=20, verbose_name='手机号码'),
            preserve_default=False,
        ),
    ]
