# Generated by Django 2.2.17 on 2021-02-05 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='地区')),
            ],
            options={
                'db_table': 'mak_Area',
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='设施名字')),
            ],
            options={
                'db_table': 'mak_facility',
                'verbose_name': '设施选项',
                'verbose_name_plural': '设施选项',
            },
        ),
        migrations.CreateModel(
            name='House_Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
            ],
            options={
                'db_table': 'mak_house_facility',
                'verbose_name': '房子配套设施',
                'verbose_name_plural': '房子配套设施',
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image', models.ImageField(upload_to='house', verbose_name='图片路径')),
            ],
            options={
                'db_table': 'mak_house_image',
                'verbose_name': '房子图片',
                'verbose_name_plural': '房子图片',
            },
        ),
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('addr', models.CharField(max_length=256, verbose_name='房子地址')),
                ('min_stay_day', models.CharField(default='1', max_length=10, verbose_name='最短入住天数')),
                ('max_stay_day', models.CharField(default='无限制', max_length=10, verbose_name='最长入住天数')),
                ('image', models.ImageField(upload_to='house', verbose_name='首页列表展示图')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Area', verbose_name='地区')),
            ],
            options={
                'db_table': 'mak_house',
                'verbose_name': '房子',
                'verbose_name_plural': '房子',
            },
        ),
        migrations.CreateModel(
            name='IndexHouseBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=20, verbose_name='轮播标题')),
                ('image', models.ImageField(upload_to='banner', verbose_name='图片')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.HouseInfo', verbose_name='房子')),
            ],
            options={
                'db_table': 'mak_IndexHouseBanner',
                'verbose_name': '房子轮播图',
                'verbose_name_plural': '房子轮播图',
            },
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('type', models.CharField(max_length=128, verbose_name='房子类型')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.HouseInfo', verbose_name='房子')),
            ],
            options={
                'db_table': 'mak_houseType',
                'verbose_name': '房子类型',
                'verbose_name_plural': '房子类型',
            },
        ),
    ]
