# Generated by Django 2.2.17 on 2021-02-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20210205_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='housetype',
            name='type_name',
            field=models.SmallIntegerField(choices=[(0, 'house'), (1, 'user'), (2, 'bed')], default=0, verbose_name='类型名称'),
        ),
    ]
