# Generated by Django 2.2.17 on 2021-02-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_housetype_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='type_name',
            field=models.CharField(choices=[(0, 'house'), (1, 'user'), (2, 'bed')], max_length=10, verbose_name='类型名称'),
        ),
    ]
