# Generated by Django 2.2.17 on 2021-02-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20210205_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_facility',
            name='facility',
            field=models.CharField(choices=[('wirelessnetwork', '无线网络'), ('shower', '热水淋浴'), ('aircondition', '空调'), ('heater', '暖气'), ('smoke', '允许吸烟'), ('drinking', '饮水设备'), ('brush', '牙具'), ('soap', '香皂'), ('slippers', '拖鞋'), ('toiletpaper', '手纸'), ('towel', '毛巾'), ('toiletries', '沐浴露、洗发露'), ('icebox', '冰箱'), ('washer', '洗衣机'), ('elevator', '电梯'), ('iscook', '允许做饭'), ('pet', '允许带宠物'), ('meet', '允许聚会'), ('accesssys', '门禁系统'), ('parkingspace', '停车位'), ('wirednetwork', '有线网络'), ('tv', '电视'), ('jinzhi', '浴缸')], max_length=30, verbose_name='房子设施'),
        ),
    ]
