# Generated by Django 2.2.17 on 2021-02-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20210205_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='isBook',
            field=models.BooleanField(default=False, verbose_name='是否被预订'),
        ),
    ]
