# Generated by Django 2.2.17 on 2021-02-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20210206_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='价格'),
        ),
    ]
