# Generated by Django 2.2.17 on 2021-02-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_auto_20210206_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='isBook',
            field=models.BooleanField(default=False, verbose_name='是否有人入住'),
        ),
    ]
