# Generated by Django 2.2.17 on 2021-02-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_auto_20210206_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_facility',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='house.HouseInfo', verbose_name='房子'),
        ),
    ]
