# Generated by Django 2.2.17 on 2021-02-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_auto_20210209_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_facility',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='house.HouseInfo', verbose_name='房子'),
            preserve_default=False,
        ),
    ]
