# Generated by Django 2.2.17 on 2021-02-09 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_auto_20210209_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexhousebanner',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.HouseImage', verbose_name='图片'),
        ),
    ]
