# Generated by Django 2.2.17 on 2021-02-05 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('comment', models.CharField(default='', max_length=256, verbose_name='评论')),
            ],
            options={
                'db_table': 'mak_comment',
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('order_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='订单id')),
                ('inTime', models.DateTimeField(verbose_name='入住时间')),
                ('outTime', models.DateTimeField(verbose_name='退房时间')),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('allPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Comment', verbose_name='评论')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.HouseInfo', verbose_name='房子')),
            ],
            options={
                'db_table': 'mak_order',
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
