# Generated by Django 2.2.17 on 2021-02-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210206_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='allPrice',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unitPrice',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='价格'),
        ),
    ]
