# Generated by Django 2.2.17 on 2021-02-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210206_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderStatue',
            field=models.SmallIntegerField(choices=[(0, '已完成'), (1, '待支付'), (2, '待入住')], default=0, verbose_name='订单状态'),
            preserve_default=False,
        ),
    ]
