# Generated by Django 2.2.17 on 2021-02-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_orderstatue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Comment', verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='house.HouseInfo', verbose_name='房子'),
        ),
    ]
